### ISSUE TITLE
Add Contributors

### ISSUE THREAD

**Issue by mahmoudalsof** [CadillacJack95/jackbot-comfyjs#1]

**Comment by mahmoudalsof** [comment]
@all-contributors please add @michaeljolley for ideas

**Comment by mahmoudalsof** [comment]
@all-contributors please add @negue for ideas

**Comment by mahmoudalsof** [comment]
@all-contributors please add @whitep4nth3r for ideas

**Comment by mahmoudalsof** [comment]
@all-contributors please add @negue for ideas

**Comment by mahmoudalsof** [comment]
@all-contributors please add @SurlyDev for ideas

**Comment by surlydev** [comment]
Wooh !
